>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()
>>> type(bg) == BaseGeometry
True
>>> type(BaseGeometry.__dict__['area'])
<class 'function'>
>>> bg.__class__.area()
Traceback (most recent call last):
TypeError: area() missing 1 required positional argument: 'self'
>>> bg.area(10)
Traceback (most recent call last):
TypeError: area() takes 1 positional argument but 2 were given
>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented
>>> type(BaseGeometry.__dict__['integer_validator'])
<class 'function'>
>>> bg.__class__.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 3 required positional arguments: 'self', 'name', and 'value'
>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
>>> bg.integer_validator(1, 1, 1)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given
>>> bg.integer_validator("foo", 3.0)
Traceback (most recent call last):
TypeError: foo must be an integer
>>> bg.integer_validator("arg", 3.14)
Traceback (most recent call last):
TypeError: arg must be an integer
>>> bg.integer_validator("Bar", "bar")
Traceback (most recent call last):
TypeError: Bar must be an integer
>>> bg.integer_validator("a", [1])
Traceback (most recent call last):
TypeError: a must be an integer
>>> bg.integer_validator("foo", None)
Traceback (most recent call last):
TypeError: foo must be an integer
>>> bg.integer_validator("key", 0)
Traceback (most recent call last):
ValueError: key must be greater than 0
>>> bg.integer_validator("key", -1000)
Traceback (most recent call last):
ValueError: key must be greater than 0
>>> bg.integer_validator("key", 98)
>>> bg.integer_validator("key", 1)
>>> bg.integer_validator("", 1)
>>> bg.integer_validator(None, 1)
>>> bg.integer_validator("Foo", (1, 2))
Traceback (most recent call last):
TypeError: Foo must be an integer
>>> bg.integer_validator("Foo", {1, 2})
Traceback (most recent call last):
TypeError: Foo must be an integer
